# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - id: tui-todo
    main: ./cmd/tui-todo
    ldflags: >-
      -X 'github.com/martijnspitter/tui-todo/internal/version.version={{ .Version }}'
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  use: github
  sort: asc
  groups:
    - title: "ðŸš€ Features"
      regexp: "^feat[(\\w)]*:.*"
      order: 0
    - title: "ðŸ› Bug Fixes"
      regexp: "^fix[(\\w)]*:.*"
      order: 1
    - title: "ðŸ”§ Maintenance"
      regexp: "^(refactor|perf|style|chore)[(\\w)]*:.*"
      order: 2
    - title: "ðŸ“š Documentation"
      regexp: "^docs[(\\w)]*:.*"
      order: 3
    - title: "ðŸ§ª Tests"
      regexp: "^test[(\\w)]*:.*"
      order: 4
    - title: "ðŸ› ï¸ Build/CI"
      regexp: "^(build|ci)[(\\w)]*:.*"
      order: 5
  filters:
    exclude:
      - "^Merge pull request"
      - "^Merge branch"
  abbrev: 7 # Short commit hash length

brews:
  - name: tui-todo
    repository:
      owner: martijnspitter
      name: homebrew-tui-todo
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: goreleaser@github.com
    homepage: "https://github.com/martijnspitter/tui-todo"
    description: "Terminal-based todo application with rich features"
    caveats: |
      Thank you for installing TUI Todo!
      Run 'todo' to start the application.
    license: "MIT" # Replace with your actual license
    directory: Formula
    install: |
      bin.install "tui-todo" => "todo"  # This renames the binary when installing
    test: |
      system "#{bin}/todo", "--version"

nfpms:
  - id: tui-todo-packages
    package_name: tui-todo
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"

    # The binary will be installed as "todo"
    bindir: /usr/local/bin
    builds:
      - tui-todo

    # Rename the binary during installation (similar to Homebrew)
    contents:
      - src: "tui-todo"
        dst: "/usr/local/bin/todo"

    # Package details
    vendor: Martijn Spitter
    homepage: https://github.com/martijnspitter/tui-todo
    maintainer: Martijn Spitter info@martijnspitter.nl
    description: Terminal-based todo application with rich features
    license: MIT

    # Dependencies (usually minimal for Go apps)
    dependencies:
      - libc6

    # Supported formats
    formats:
      - deb
      - rpm
      - apk

    # .deb specific
    deb:
      lintian_overrides:
        - statically-linked-binary

    # Package recommends
    recommends:
      - terminal-with-utf8-support

snapcrafts:
  - id: tui-todo
    name: tui-todo
    summary: Terminal-based todo application
    description: |
      A powerful terminal-based todo application built with Go.
      Manage your tasks efficiently without leaving the command line.
    grade: stable
    confinement: strict
    apps:
      tui-todo:
        command: todo
        plugs: [home, network, desktop-legacy]
